spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/instagram
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging.level:
  org:
    hibernate:
      SQL: debug
#    apache:
#      coyote:
#        http11: debug

file:
  dir: C:/Users/chlwn/Desktop/myproject1/instragram/src/main/resources/static/files/

server:
  servlet:
    session:
      tracking-modes: COOKIE
